import Header from "../components/Header/Header"
import Head from 'next/head'
import Datas from '../data.json'
import index from '../styles/index.module.scss'
import { useMemo } from "react"

export function getServerSideProps(context) {

  let planet = 'Mercury'
  if (context.params.planet) {
    planet = context.params.planet[0]
  }

  return {
    props: {
      planet
    }
  }
}


export default function Home({ planet }) {

  const currentPlanet = useMemo(() => {
    return Datas.find(data => data.name === planet)
  }, [planet])

  if (!currentPlanet) {
    return <div>
      Planeta não existe
    </div>
  }


  return (

    <div>
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Antonio:wght@400;500&family=Spartan:wght@400;700&display=swap" rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" />
        <title>Planets</title>
      </Head>

      <main>
        <Header />

        <section className={index.section}>

          <div className={index.informations}>
            <div className="image">
              <img src={ currentPlanet.images.planet} />
            </div>

            <div className={index.text}>

              <div className={index.planetName}>
                <h2>{currentPlanet.name}</h2>
              </div>

              <div className={index.paragraph}></div>
              <div className={index.source}></div>
            </div>

          </div>

          <div className={index.description}>

          </div>

        </section>
      </main>


    </div>
  )
}
