import Header from "../components/Header/Header"
import Head from 'next/head'
import Datas from '../data.json'
import index from '../styles/index.module.scss'
import { useMemo, useState } from "react"

export function getServerSideProps(context) {

  let planet = 'Mercury'
  if (context.params.planet) {
    planet = context.params.planet[0]
  }

  return {
    props: {
      planet
    }
  }
}


export default function Home({ planet}) {

  const [ state, setState ] = useState('overview')

  const currentPlanet = useMemo(() => {
    return Datas.find(data => data.name === planet)
  }, [planet])

  const attribute = useMemo(()=>{
    return currentPlanet[state]
  }, [currentPlanet, state])


  if (!currentPlanet) {
    return <div>
      Planeta não existe
    </div>
  }

  const renderImage = useMemo(()=>{
    if(state === 'overview'){
      return (
        <>
          <img src={ currentPlanet.images.planet } className={`${index.image} ${currentPlanet.name.toLocaleLowerCase()}`}/>
    
        </>
      )
    }

    else if(state === 'structure'){
      return (
        <>
          <img src={ currentPlanet.images.internal } className={`${index.image} ${currentPlanet.name.toLocaleLowerCase()}`}/>
  
        </>
      )
    } 
    else{
      return (
        <>
          <img src={ currentPlanet.images.planet } className={`${index.image} ${currentPlanet.name.toLocaleLowerCase()}`}/>
          <div className={`imageSurface ${currentPlanet.name.toLocaleLowerCase()}`}></div>     
        </>
      )
    }
  }, [currentPlanet, state])  


  return (

    <div>
      <Head>
        <link href="https://fonts.googleapis.com/css2?family=Antonio:wght@400;500&family=Spartan:wght@400;700&display=swap" rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" />
        <title>Planets</title>
      </Head>

      <main>
        <Header changeState={state => setState(state)}/>
        

        <section className={index.section}>

          <div className={index.informations}>
            <div className="image">
              {renderImage}
            </div>

            <div className={index.text}>

              <div className={index.planetName}>
                <h2>{currentPlanet.name.toLocaleUpperCase()}</h2>
              </div>

              <div className={index.paragraph}>
                <p>{attribute.content}</p>
              </div>

              <div className={index.source}>
                <span>Source:</span>
                <a href={attribute.source}>WIkipédia</a>
              </div>
            </div>

          </div>

          <div className={index.description}>

          </div>

        </section>
      </main>


    </div>
  )
}
