import Header from "../components/Header/Header"

export default function Home() {
  return (
    <div>
      <head>
          <title>Planets</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </head>

      <main>

      <Header />
      </main>

     
    </div>
  )
}
